CREATE TABLE [dbo].[AAAERC7] (
  [Account] [varchar](50) NULL,
  [Year] [int] NULL,
  [Month] [int] NULL,
  [fio] [varchar](500) NULL,
  [PersUstr] [varchar](250) NULL,
  [SaldoNachGaz] [float] NULL,
  [SaldoNachPenya] [float] NULL,
  [SaldoNachSudVzysk] [float] NULL,
  [SaldoNachSudIzder] [float] NULL,
  [SaldoNachSHtraf] [float] NULL,
  [SaldoNachDopUslug] [float] NULL,
  [SaldoNachItog] [float] NULL,
  [OplachenoGaz] [float] NULL,
  [OplachenoPenya] [float] NULL,
  [OplachenoSudVzysk] [float] NULL,
  [OplachenoSudIzder] [float] NULL,
  [OplachenoSHtraf] [float] NULL,
  [OplachenoDopUslug] [float] NULL,
  [OplachenoItog] [float] NULL,
  [PredPokaz] [float] NULL,
  [TekPokaz] [float] NULL,
  [Cena] [float] NULL,
  [Kolvo] [varchar](8000) NULL,
  [SummaNach] [float] NULL,
  [SummNachislGaz] [float] NULL,
  [SummNachislPenya] [float] NULL,
  [SummNachislVzysk] [float] NULL,
  [SummNachislIzder] [float] NULL,
  [SummNachislSHtraf] [float] NULL,
  [SummNachislDopUslug] [float] NULL,
  [SummNachislItog] [float] NULL,
  [SaldoKonecGaz] [float] NULL,
  [SaldoKonecPenya] [float] NULL,
  [SaldoKonecVzysk] [float] NULL,
  [SaldoKonecIzder] [float] NULL,
  [SaldoKonecSHtraf] [float] NULL,
  [SaldoKonecDopUslug] [float] NULL,
  [SaldoKonecItog] [float] NULL,
  [Primechanie] [varchar](250) NULL,
  [Street] [varchar](50) NULL,
  [HouseNumber] [varchar](10) NULL,
  [HouseNumberChar] [varchar](20) NULL,
  [Flat] [varchar](20) NULL
)
ON [PRIMARY]
GO