CREATE TABLE [dbo].[PDVDGO] (
  [IDPDVDGO] [int] IDENTITY,
  [IDTypePDVDGO] [int] NOT NULL,
  [IDDocumentVDGO] [int] NULL,
  [Value] [varchar](2000) NULL,
  CONSTRAINT [PK_PDVDGO] PRIMARY KEY CLUSTERED ([IDPDVDGO])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[PDVDGO]
  ADD CONSTRAINT [FK_PDVDGO_DocumentVDGO] FOREIGN KEY ([IDDocumentVDGO]) REFERENCES [dbo].[DocumentVDGO] ([IDDocumentVDGO]) ON DELETE CASCADE
GO

ALTER TABLE [dbo].[PDVDGO]
  ADD CONSTRAINT [FK_PDVDGO_PDVDGO] FOREIGN KEY ([IDTypePDVDGO]) REFERENCES [dbo].[TypePDVDGO] ([IDTypePDVDGO])
GO