select PCM.IDPERSONALCABINETMESSAGE, PCM.MESSAGETITLE, PCM.MESSAGEBODY, PC.PCEMAIL, PCM.MESSAGETYPE, PCM.ACCOUNT
from PERSONALCABINETMESSAGE as PCM
  join PERSONALCABINET as PC on PC.ACCOUNT = PCM.ACCOUNT
where PCM.NEEDSENDMESSAGE = 1;


select ACCOUNT, PCPASS, PCEMAIL, IDPERSONALCABINET
from PERSONALCABINET
where len(isnull(PCPASS, '')) > 0
  and len(isnull(PCEMAIL, '')) > 0;